# Generated by Django 4.2.17 on 2025-02-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_images/')),
                ('text', models.CharField(default='ГЛАВНЫЙ ТЕКСТ', max_length=255)),
            ],
        ),
    ]
