# Generated by Django 4.2.17 on 2025-02-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSectionSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero_second/')),
            ],
        ),
    ]
